### ISSUE TITLE
Failed to start due to failure to launch embedded Tomcat

### ISSUE THREAD

**Issue by bodonova** [IBM/speech-customization-ui#6]
I installed the code on MacOS, but when I execute the command "mvn spring-boot:run" I get an error (see extract from console output below):

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-01-22 15:57:49.333 ERROR 46500 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar:2

**Comment by afaisman** [comment]
@bodonova do you have node js installed?

**Comment by bodonova** [comment]
Yes node js is installed
`$ node -v
v14.13.1
`

**Comment by SRSaddler** [comment]
Having the same issue. @bodonova did you resolve?

**Comment by bodonova** [comment]
It turned out I had JRE installed rather than JDK. When I installed JDK it worked.

**Comment by marconoel** [comment]
Thanks @bodonova
